### ISSUE TITLE
box math and reflection

### ISSUE THREAD

**Issue by tsulej** [Sophia-Gold/bitwise#1] opened 2017-09-14 20:59 UTC
It's just a suggestion. For math operations I would test all code against reflection and boxed math and add type hints. To get maximum efficiency. Just add two following lines at the top of the code:

`(set! *warn-on-reflection* true)`
`(set! *unchecked-math* :warn-on-boxed)`

**Comment by Sophia-Gold** [comment] 2017-09-16 21:45
Thanks for pointing that out! To be honest, I haven't yet intended this library to be anywhere near production quality; it's currently just a catch-all for odd curiosities. 

My general practice is to test for reflection when called for...I just hadn't noticed the small number of cases I added where it was actually called for here. I'll commit those patches shortly.

Boxed math is a whole other issue. I largely ignore it since my performance bottlenecks are in collections, but given the amount of Java interop I'm using here I should take it into account and possibly even see whether some of these functions finally give me a use case for Zach Tellman's [primitive-math](https://github.com/ztellman/primitive-math) library.

I have some free time this weekend so we'll see how far I get with boxing. I'm also hoping to add some new features I've been playing with (Toffoli and Fredkin gates) :slightly_smiling_face:

**Comment by Sophia-Gold** [comment] 2017-09-18 06:34
Okay, I just committed this: https://github.com/Sophia-Gold/bitwise/commit/f2ac67d51f92fb38c82e5cffb60a663126f3b264. 

I used the [primitive-math](https://github.com/ztellman/primitive-math) operators unqualified since there were only a handful of higher-order cases, many of which I could handle by using the `+'` core functions (which make more sense for `reduce` anyway). For the rest I aliased clojure.core as `cc` to call the original versions.

Tbh, I have some degree of trepidation about the performance vs. legibility tradeoff here. To eliminate all the boxing I had to add a lot of coercion and type hints that I wouldn't have otherwise (also makes me wish I had taken this library seriously and written a full test suite to begin with...). I may create a new branch for future commits in case I decide to roll this one back.

@tsulej, I'm going to close this, but please do let me know what you think if/when you get a chance!

**Closed as completed by Sophia-Gold** 2017-09-18 06:34 UTC

**Comment by tsulej** [comment] 2017-09-18 08:25
My opinion is that math / calculation libs should be as fast as possible. Even if readability is worse. I know that type hinting limits general use of functions but vast of maths operates on doubles or longs (especially low level ones like inverse-sqrt or bit-count). When you decide to release your lib someday, end-user will possibly hit some bottlenecks. In my Clojure2d scripts I often call some functions millions times and I learnt to optimize code as much as possible to have execution times comparable to Java/Processing.

Regarding primitive-math. Clojure internally has the same primitive functions built in. When you type hint and turn off checked math you have exactly the same preformance.

**Comment by tsulej** [comment] 2017-09-18 08:28
Just for reference, link to primitive code in Clojure Numbers: https://github.com/clojure/clojure/blob/clojure-1.9.0-alpha14/src/jvm/clojure/lang/Numbers.java#L1416

**Comment by Sophia-Gold** [comment] 2017-09-18 11:52
I didn't think of most of this library as particularly numerically intensive. Obviously that's true for the functions you pointed out, though.

The primitive-math library covers a much wider range of operators, particularly equality and bit shifting. I'm also not sure turning off overflow checking gives the same performance since it still doesn't warn you when reflection is used to determine the type. There are times that can occur even when the initial arguments have type hints and `warn-on-reflection` won't throw warnings for math operations.

**Comment by Sophia-Gold** [comment] 2017-09-19 22:29
To follow up on this: I confirmed with the Clojure core team that, although the primitive-math library was developed independently around the same time as unchecked-math, my intuition was correct that for the overlapping functions `warn-on-boxed` won't catch 100% of cases—particularly in return paths.

**Comment by tsulej** [comment] 2017-09-20 07:32
You're right. I observed some performance gain after switching to primitive-math. Clojure definitely has too many options to choose during compilation. Thank you very much for discussion, it was very helpful.
